sudo: false
language: node_js
node_js:
- node
script:
  - npm run build
  - npm run build-storybook
deploy:
  provider: npm
  email: tdgroen@zaibot.net
  skip_cleanup: true
  api_key:
    secure: XUBX7GK93mPqZXtWoc3mUfW3qd3QfiqQCxDX32NE/h4H+OIctHQIstqoe9XnWDMdKQFqLVlLFnHgWafM00nb0Sa/S0vCf+nVkdbLHwRDqaoYsYDWDmzQVXC8TS+rm3TI6eWiV7dBxF5MkbJrXi4ORxU/40g6rUOiIJRIvfgOtRr1qiTc7/+38zzKSDzWn2JLd1RzoHUehasY0lDrHVSf/dcCFB2scGX6+5WtGvFAKgThn03efuRNzX8c5mIDU+18wdqntP9lht0zJxVjKjVIklg3IiYNCpCR5leWpD/w8M2zosBPh3W7XnhGVyVtsmATp3xUYVM5rljt92aIOVaBcuzUqzQU3sXRE0x26oLllMOR6Iu+0T+zkOKt+q/RDogj55x2814a5CsCaGh1PZ26Ai6Z61qmVJEh93pDNpk3Xs++t9CW5BpARHX7EG2dvp9S2hHYVRK/sJUZWH6jv+gn+BA/C7n/Towko0qW+aVm26EBXrRMo8AzLYBoBMRSiXWhpecTAOwOpUMHxyFa0LQL3FbmQvlYypCsVt0Wu99ZwYPcjVmvqkFrWcPaxST6bYMvNuZxiQ0J9U2zIGakyq/s8fJiviFRna9WRtoGeWV2/fyG+MNXFAcrx50Q/7e5mW6h8zv2PUfDliqY3O3d7Sd+Z1oZYzR3Q6FFDk1nGCms5ts=
  on:
    tags: true
    repo: Zaibot/react-dnd
deploy:
  provider: pages
  local-dir: storybook-static
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
