sudo: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email: tdgroen@zaibot.net
  skip_cleanup: true
  api_key:
    secure: kffplCxVCyMVDxNai20XM/vFa+1/gXx77cNbR6J6y/ZdLUIL2oh4QXIR+3QAOe0UdDRyhr78P9Ti3uqCvei9RXKPDIbY5cqi0iZjIxrFLPTW/OtAQqh9rZonKsWLGyKvtukM8/LHPUU5fdn6V5sPWkXZZlVjMQjHaZSs8oyTuZg8of6CFvnt89s24s5R71vVUY2Mm09IG+DeneheeSxlgfBGMNDJF44UKiQ5WP51KrXHFavpA9ONdvBB9BlmmqYG/Evq6TH8WzJlySjdjWOFSkMg+CjLIrbOuPkhwvPtv1yGGauAHYf38LdRV9uHDr8PDBFKAOgyjHwwik8nfgfNWrHeAMcAVOgRa5J8zE9tBRGP5tyyCRs7CiAN5suEJ7YnjZhCpHjNa0DEQkw6AQ/gJTORw+MsqyCNFDMqeI8mqLJIwWPLIxttOpGHj8f66bpmNpGRIv/NYwxMD7nkehMMrOHcNLu0A05e/P7/klWZImXKJro1sXrBiE5FRXqQ+IO7P+KYE02HKi5z9eU8P0UrC5b1MTSmvqAaoizVh4gNde8EXWETFlDBKw4VODXEkCFnhOlaF9nWIbsbDI2Ia7dRfmLyzf9vqHZ7H/WIJAk1+GP7aCESY8kP2oMUTISQtJ0+zl/eJDtzPqlQk68N6zgU5uK1OK0eBIeusEdVkl+uhWo=
  on:
    tags: true
    repo: Zaibot/react-dnd
